# Generated by Django 4.1.2 on 2024-03-11 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=28)),
                ('text', models.TextField()),
                ('like', models.IntegerField()),
                ('emo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=29), default=list, size=None)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=28)),
                ('password', models.CharField(max_length=28)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
