# Generated by Django 4.1.2 on 2024-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=28)),
                ('text', models.TextField()),
                ('like', models.IntegerField()),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=28)),
                ('password', models.CharField(max_length=28)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='int_info',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
