# Generated by Django 4.1.2 on 2024-08-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_rename_author_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='n1',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n10',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n11',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n12',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n13',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n14',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n15',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n16',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n17',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n18',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n19',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n2',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n20',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n21',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n22',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n23',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n3',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n4',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n5',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n6',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n7',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n8',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='n9',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='surname',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
