from django.db import models

# Create your models here.
class data(models.Model):
    name = models.CharField(max_length=100, default = "-")
    surname = models.CharField(max_length=100, default = "-")
    age = models.CharField(max_length=100, default = "-")
    gender = models.CharField(max_length=100, default = "-")
    n1 = models.CharField(max_length=100, default = "-")
    n2 = models.CharField(max_length=100, default = "-")
    n3 = models.CharField(max_length=100, default = "-")
    n4 = models.CharField(max_length=100, default = "-")
    n5 = models.CharField(max_length=100, default = "-")
    n6 = models.CharField(max_length=100, default = "-")
    n7 = models.CharField(max_length=100, default = "-")
    n8 = models.CharField(max_length=100, default = "-")
    n9 = models.CharField(max_length=100, default = "-")
    n10 = models.CharField(max_length=100, default = "-")
    n11 = models.CharField(max_length=100, default = "-")
    n12 = models.CharField(max_length=100, default = "-")
    n13 = models.CharField(max_length=100, default = "-")
    n14 = models.CharField(max_length=100, default = "-")
    n15 = models.CharField(max_length=100, default = "-")
    n16 = models.CharField(max_length=100, default = "-")
    n17 = models.CharField(max_length=100, default = "-")
    n18 = models.CharField(max_length=100, default = "-")
    n19 = models.CharField(max_length=100, default = "-")
    n20 = models.CharField(max_length=100, default = "-")
    n21 = models.CharField(max_length=100, default = "-")
    n22 = models.CharField(max_length=100, default = "-")
    n23 = models.CharField(max_length=100, default = "-")
